#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# SSO Frontend — Standalone Deployment Script
#
# Runs ON the server in the project directory. Builds the React/Vite SPA and
# copies static output to /root/apps/sso-frontend/ for nginx to serve.
#
# Usage:
#   ./deploy.sh                  — rolling update (pull → build → copy)
#   ./deploy.sh fresh-install    — wipe build artifacts + node_modules, rebuild
#
# Prerequisites (on the server):
#   • Node.js 18+ and npm
#   • Git
#
# Nginx serves the output at /sso/ via:
#   location /sso/ {
#       alias /root/apps/sso-frontend/;
#       try_files $uri $uri/ /sso/index.html;
#   }
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE="${1:-}"
SERVE_DIR="/var/www/sso-frontend"

# Production config — SSO backend is served at /sso-server/ via nginx
SSO_API_URL="http://buildwithkulshresth.com/sso-server"

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()  { echo -e "${CYAN}[$(date '+%H:%M:%S')]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
ok()   { echo -e "${GREEN}[OK]${NC} $*"; }
die()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── fresh-install: triple confirmation ───────────────────────────────────────
if [[ "$MODE" == "fresh-install" ]]; then
  echo ""
  echo -e "${RED}${BOLD}╔══════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${RED}${BOLD}║          ⚠  FRESH SSO FRONTEND INSTALL WARNING  ⚠            ║${NC}"
  echo -e "${RED}${BOLD}╠══════════════════════════════════════════════════════════════╣${NC}"
  echo -e "${RED}${BOLD}║  This will PERMANENTLY DELETE:                               ║${NC}"
  echo -e "${RED}${BOLD}║    • dist/            — current live static build            ║${NC}"
  echo -e "${RED}${BOLD}║    • node_modules/    — all installed packages               ║${NC}"
  echo -e "${RED}${BOLD}║    • $SERVE_DIR — live served files    ║${NC}"
  echo -e "${RED}${BOLD}║                                                              ║${NC}"
  echo -e "${RED}${BOLD}║  The SSO UI will go dark until the new build finishes.       ║${NC}"
  echo -e "${RED}${BOLD}╚══════════════════════════════════════════════════════════════╝${NC}"
  echo ""

  for i in 1 2 3; do
    case $i in
      1) MSG="Are you sure you want a fresh SSO frontend install? [yes/no]: " ;;
      2) MSG="[Confirmation $i/3] The SSO admin UI will go dark. Continue? [yes/no]: " ;;
      3) MSG="[Confirmation 3/3] LAST CHANCE — type 'yes' to wipe and rebuild: " ;;
    esac
    read -rp "$(echo -e "${RED}${BOLD}$MSG${NC}")" ANSWER
    [[ "$ANSWER" == "yes" ]] || { echo "Aborted. Nothing changed."; exit 0; }
  done

  log "Wiping build artifacts..."
  rm -rf "$SCRIPT_DIR/dist" "$SCRIPT_DIR/node_modules" "$SERVE_DIR"
  ok "Wipe complete. Proceeding with fresh install..."
  echo ""
fi

# ── Pre-flight checks ─────────────────────────────────────────────────────────
log "Checking prerequisites..."
command -v node >/dev/null || die "Node.js not installed."
command -v npm  >/dev/null || die "npm not installed."
ok "Prerequisites OK (Node $(node --version))."

# ── Pull latest code ──────────────────────────────────────────────────────────
log "Pulling latest code..."
cd "$SCRIPT_DIR"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
git pull origin "$CURRENT_BRANCH"

if [[ "${_SSO_FE_PULLED:-0}" != "1" ]]; then
  export _SSO_FE_PULLED=1
  exec "$0" "$@"
fi

# ── Install dependencies ──────────────────────────────────────────────────────
log "Installing dependencies..."
npm ci

# ── Write production env ──────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/.env.production" <<EOF
# Auto-generated by deploy.sh on $(date)
# SSO backend public URL — proxied by nginx at /sso-server/ → port 9000
VITE_SSO_API_URL=${SSO_API_URL}
EOF
ok "Written .env.production (VITE_SSO_API_URL=${SSO_API_URL})"

# ── Build ─────────────────────────────────────────────────────────────────────
log "Building React/Vite SPA (base path: /sso/)..."
npm run build -- --base /sso/
[ -d "$SCRIPT_DIR/dist" ] || die "Build failed — dist/ not found."
ok "Build complete."

# ── Deploy to serve directory ─────────────────────────────────────────────────
log "Copying build output to $SERVE_DIR ..."
mkdir -p "$SERVE_DIR"
rm -rf "${SERVE_DIR:?}"/*
cp -r "$SCRIPT_DIR/dist/"* "$SERVE_DIR/"
ok "Files deployed to $SERVE_DIR"

# ── Reload Nginx ──────────────────────────────────────────────────────────────
if command -v nginx >/dev/null 2>&1; then
  log "Reloading Nginx..."
  nginx -t && systemctl reload nginx && ok "Nginx reloaded." || warn "Nginx reload failed."
fi

echo ""
echo -e "${GREEN}${BOLD}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  SSO Frontend deploy complete${NC}  [mode: ${MODE:-rolling}]"
echo -e "${GREEN}${BOLD}════════════════════════════════════════════════════════${NC}"
log "  SSO Admin UI : http://buildwithkulshresth.com/sso/"
log "  Served from  : $SERVE_DIR (nginx alias)"
echo ""
